### ISSUE TITLE
v0.1.x - Output a dependency report file

### ISSUE THREAD

**Issue by rbuisson** [mekomsolutions/dependency-tracker-maven-plugin#1]
### Acceptance criteria (to be improved along the way)
- Able to run a Maven command that outputs a "dependency report" file, which contains the exact dependency versions (including uniquely identified snapshots) used during the build.
- Dependency report to be sorted alphabetically so to facilitate comparison.
- Should be run by default before or at the `compile` Maven phase.
- (Nice to have) Able to publish the dependency report as part of the build profile of the project.
- (Nice to have) Able to compare the dependency report from a remote artifact with the one build locally.
- Documentation of a Quick Start guide and a documentation of all available options.
- (Nice to have) Plugin hosted on [Codehaus](https://mvnrepository.com/artifact/org.codehaus)
- (Nice to have) Plugin to use hashes that are pre-generated by maven instead of re-computing them, if these can be fetched from a remote repo then we could avoid unnecessary downloads of the dependencies themselves which in turn would mean we avoid execution of unnecessary later lifecycle phases i.e. the plugin can be run as early as the `process-sources` phase.

**Comment by wluyima** [comment]
- Implemented tracking and generation of the dependency report containing mappings between dependency and hash

**Comment by wluyima** [comment]
This is completed (minus the nice to haves), please refer the project readme for usage
